language: node_js
sudo: false
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    - ubuntu-toolchain-r-test
    packages:
    - google-chrome-stable
    - g++-4.8
node_js:
- '0.12'
- '4.2'
- '5.1'
before_script:
- npm install -g bower polylint web-component-tester
- bower install
script:
  - xvfb-run wct
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
env:
  global:
  - CXX='g++-4.8'
  - secure: g/QhfmIKZNVkIhHfDbk8QRK92zQevBMbmVUlnQoglaTC7Rs5O8IYquvfYqkv+APuG003r70yKsNSV3S/el9nvHVnfyl18yyJdb8wE6sngVT890zmDQXtOfFE+OO/O4hyzKNbN6v0QjY/n4zUB84Sp/0NSDX49liZVd/yn1HM6lA2Zj/pYlfNWVX77DdYLhByR6vClWBSRwNO3PYgTA6U6zSaWTcsNV0XGrW96xjHuRByH0daOM7J4FQKJTRSRkvUCePqWdALZBcgemWmRTk2rGMx9+LnuBNl++xxHg9UrFxLKvvTrZY8SpxOdQDzC7PNFiEGQNNXI98RG9nkSNPDZNrc1vPbSsmibmwKno2DBb5//VMWxvkjiS4WNjEkOgRreEX4C8yBdP2p9KAkbkMOkqskYFLa/xvoNhG9A0GNjOgIXjUfeLXIYCDAsptI3mTwhJi9PZ/vmu7UiJqcGiRaSv8ORdsGpiJbsm95njhtOWsAwj3wPKFSI18ex1hxPRtrz3U6Ton1OEvI54UspPunm3AH6XIEPSJbdQzzRXzfa9pjUQj3DWsZZkf/ZbyZd7IEgGlm7l621DbxPi6tS22EH5bkoU+FQ+St68nlFkhwsi3O2g6Q3HZt3qD2nytLSsxlWj2Xy51BgA2AeOEeb4HGzGdclp9KnEraR4KTXYjNWlI=
  - secure: ebmOZWMKFzTtlZQeYJywTeaXNwpSeDf+ike9g+LWKdEvvkEtQjexpVwwWorDJMmBSGfuAfbLApAcqunIZkMakvD7qhCx13VVyuXrUu+lnFIFYqxRDnolxA1tjeGd3In5cYFbNAnimx1bUR0K99KMCdgSLbU5bYscfQKI/1KGupRKlFyfKHoVzwSnKQejARiZoTs/eTu0wlcIYzyt2rvXC90QiII9DIDvGIrZ9FoIVzSF/zhpRtGPVR8ov8w223CnIlneVhG5wzNFdeAuOlCfrbCkrxJhnip08w5Rdg633OCbqA35gIK7xqT/Z/UiLfTdzgJjYPhVs+kEEVFbNMedArfQCXdHGi0i43SNKuz5QOSKrZGO9cKsjfCW/CsfRismKUHbxr1r+52w45KmP8pQPruMSyus2u5biCEsjWELjcwdpgZyPl2zSeabDro/jUJa42qCpwXxUstSV/8yTjtSpDAEqAU4JgwOyV5ZmW+RJSEADvcz8/cE51INYyZXs/Pg6bLgqn1Y+54p4sDuSdJSZzK4slv2qduovlJgfzPlAypBBGPhxkqu6opGoTeUclv4kHoP8k1YHyOzCXJal8nBtKkuV3Ib95Ko8QROU7IiTn7DZ+illZZ91wK4xrjVojQ1/f15rmbImKTEV3GPFNyEm+qVGBqfakSXqfAvrEFgHAs=
